### ISSUE TITLE
Error Download

### ISSUE THREAD

**Issue by giannidimanno89** [Leone25/hub-young-downloader#4]
Hi, when i try to download the content i got this message on browser console.

script.js:53          GET https://ms-mms.hubscuola.it/public/5436428/5436430/a7fcca30792971320def25a5d30820cc.jpg 404 (Not Found)
download @ script.js:53
await in download (async)
(anonymous) @ script.js:16
JpegEmbedder.js:41 Uncaught (in promise) Error: SOI not found in JPEG
    at Function.<anonymous> (JpegEmbedder.js:41:27)
    at tslib.es6.js:100:23
    at Object.next (tslib.es6.js:81:53)
    at tslib.es6.js:74:71
    at new Promise (<anonymous>)
    at i (tslib.es6.js:70:12)
    at t.for (JpegEmbedder.js:35:16)
    at e.<anonymous> (PDFDocument.js:958:59)
    at tslib.es6.js:100:23
    at Object.next (tslib.es6.js:81:53)

**Comment by Leone25** [comment]
hmmm interesting

seems like they updated something, will look into it when I can

**Comment by Leone25** [comment]
I have now made an updated that fixes it, please look at the new README file for instructions
